-- MySQL Script generated by MySQL Workbench
-- Wed May 14 12:18:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema globeDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema globeDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `globeDB` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `globeDB` ;

-- -----------------------------------------------------
-- Table `globeDB`.`Accommodation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`Accommodation` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globeDB`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`Account` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `paymentCredential` VARCHAR(45) NULL DEFAULT NULL,
  `rating` DOUBLE NULL DEFAULT NULL,
  `description` VARCHAR(140) NULL DEFAULT NULL,
  `type` ENUM('user', 'agency', 'guest') NULL DEFAULT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globeDB`.`Attraction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`Attraction` (
  `placeID` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`placeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globeDB`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`City` (
  `placeID` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `country` VARCHAR(45) NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`placeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globeDB`.`Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`Flight` (
  `id` VARCHAR(45) NOT NULL,
  `departureTime` DOUBLE NULL DEFAULT NULL,
  `arrivalTime` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globeDB`.`Itinerary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`Itinerary` (
  `itineraryID` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(120) NOT NULL,
  `daysNumber` INT NOT NULL,
  `inFlight` VARCHAR(45) NULL DEFAULT NULL,
  `outFlight` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`itineraryID`),
  INDEX `fk_inFlight_idx` (`inFlight` ASC) VISIBLE,
  INDEX `fk_outFlight_idx` (`outFlight` ASC) VISIBLE,
  CONSTRAINT `fk_inFlight`
    FOREIGN KEY (`inFlight`)
    REFERENCES `globeDB`.`Flight` (`id`),
  CONSTRAINT `fk_outFlight`
    FOREIGN KEY (`outFlight`)
    REFERENCES `globeDB`.`Flight` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globeDB`.`Day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`Day` (
  `dayNum` INT NOT NULL,
  `itineraryID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`itineraryID`, `dayNum`),
  INDEX `fk_itinerary_idx` (`itineraryID` ASC) VISIBLE,
  CONSTRAINT `fk_itinerary_d`
    FOREIGN KEY (`itineraryID`)
    REFERENCES `globeDB`.`Itinerary` (`itineraryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globeDB`.`Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`Type` (
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globeDB`.`ItineraryType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`ItineraryType` (
  `itineraryID` VARCHAR(45) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `fk_itinerary_idx` (`itineraryID` ASC) VISIBLE,
  INDEX `fk_type_idx` (`type` ASC) VISIBLE,
  CONSTRAINT `fk_itinerary_it`
    FOREIGN KEY (`itineraryID`)
    REFERENCES `globeDB`.`Itinerary` (`itineraryID`),
  CONSTRAINT `fk_type`
    FOREIGN KEY (`type`)
    REFERENCES `globeDB`.`Type` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globeDB`.`Proposal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`Proposal` (
  `id` VARCHAR(45) NOT NULL,
  `itineraryID` VARCHAR(45) NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `description` VARCHAR(120) NULL DEFAULT NULL,
  `user` VARCHAR(45) NULL DEFAULT NULL,
  `agency` VARCHAR(45) NULL DEFAULT NULL,
  `accepted` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_itinerary_pro_idx` (`itineraryID` ASC) VISIBLE,
  INDEX `fk_user_pro_idx` (`user` ASC) VISIBLE,
  INDEX `fk_agency_pro_idx` (`agency` ASC) VISIBLE,
  CONSTRAINT `fk_agency_pro`
    FOREIGN KEY (`agency`)
    REFERENCES `globeDB`.`Account` (`username`),
  CONSTRAINT `fk_itinerary_pro`
    FOREIGN KEY (`itineraryID`)
    REFERENCES `globeDB`.`Itinerary` (`itineraryID`),
  CONSTRAINT `fk_user_pro`
    FOREIGN KEY (`user`)
    REFERENCES `globeDB`.`Account` (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globeDB`.`Request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`Request` (
  `id` VARCHAR(45) NOT NULL,
  `user` VARCHAR(45) NULL DEFAULT NULL,
  `agency` VARCHAR(45) NULL DEFAULT NULL,
  `accepted` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(120) NULL DEFAULT NULL,
  `days` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_req_idx` (`user` ASC) VISIBLE,
  INDEX `fk_agency_req_idx` (`agency` ASC) VISIBLE,
  CONSTRAINT `fk_agency_req`
    FOREIGN KEY (`agency`)
    REFERENCES `globeDB`.`Account` (`username`),
  CONSTRAINT `fk_user_req`
    FOREIGN KEY (`user`)
    REFERENCES `globeDB`.`Account` (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globeDB`.`accountItinerary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`accountItinerary` (
  `account` VARCHAR(45) NOT NULL,
  `itineraryID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`account`, `itineraryID`),
  INDEX `fk_itinerary_ai_idx` (`itineraryID` ASC) VISIBLE,
  CONSTRAINT `fk_account_ai`
    FOREIGN KEY (`account`)
    REFERENCES `globeDB`.`Account` (`username`),
  CONSTRAINT `fk_itinerary_ai`
    FOREIGN KEY (`itineraryID`)
    REFERENCES `globeDB`.`Itinerary` (`itineraryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globeDB`.`accountProposal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`accountProposal` (
  `account` VARCHAR(45) NOT NULL,
  `proposalID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`account`, `proposalID`),
  INDEX `fk_proposal_ap_idx` (`proposalID` ASC) VISIBLE,
  CONSTRAINT `fk_account_ap`
    FOREIGN KEY (`account`)
    REFERENCES `globeDB`.`Account` (`username`),
  CONSTRAINT `fk_proposal_ap`
    FOREIGN KEY (`proposalID`)
    REFERENCES `globeDB`.`Proposal` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globeDB`.`accountRequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`accountRequest` (
  `account` VARCHAR(45) NOT NULL,
  `requestID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`account`, `requestID`),
  INDEX `fk_request_ar_idx` (`requestID` ASC) VISIBLE,
  CONSTRAINT `fk_account_ar`
    FOREIGN KEY (`account`)
    REFERENCES `globeDB`.`Account` (`username`),
  CONSTRAINT `fk_request_ar`
    FOREIGN KEY (`requestID`)
    REFERENCES `globeDB`.`Request` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globeDB`.`agencyType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`agencyType` (
  `agency` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`agency`, `type`),
  INDEX `fk_type_at_idx` (`type` ASC) VISIBLE,
  CONSTRAINT `fk_agency_at`
    FOREIGN KEY (`agency`)
    REFERENCES `globeDB`.`Account` (`username`),
  CONSTRAINT `fk_type_at`
    FOREIGN KEY (`type`)
    REFERENCES `globeDB`.`Type` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globeDB`.`dayAttraction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`dayAttraction` (
  `attractionID` VARCHAR(45) NOT NULL,
  `itineraryID` VARCHAR(45) NOT NULL,
  `dayNum` INT NOT NULL,
  PRIMARY KEY (`attractionID`, `itineraryID`, `dayNum`),
  INDEX `fk_day_idx` (`itineraryID` ASC, `dayNum` ASC) VISIBLE,
  CONSTRAINT `fk_attraction`
    FOREIGN KEY (`attractionID`)
    REFERENCES `globeDB`.`Attraction` (`placeID`),
  CONSTRAINT `fk_day_a`
    FOREIGN KEY (`itineraryID` , `dayNum`)
    REFERENCES `globeDB`.`Day` (`itineraryID` , `dayNum`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globeDB`.`dayCity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`dayCity` (
  `cityID` VARCHAR(45) NOT NULL,
  `itineraryID` VARCHAR(45) NOT NULL,
  `dayNum` INT NOT NULL,
  PRIMARY KEY (`cityID`, `itineraryID`, `dayNum`),
  INDEX `fk_day_c_idx` (`itineraryID` ASC, `dayNum` ASC) VISIBLE,
  CONSTRAINT `fk_city`
    FOREIGN KEY (`cityID`)
    REFERENCES `globeDB`.`City` (`placeID`),
  CONSTRAINT `fk_day_c`
    FOREIGN KEY (`itineraryID` , `dayNum`)
    REFERENCES `globeDB`.`Day` (`itineraryID` , `dayNum`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globeDB`.`itineraryAccommodation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`itineraryAccommodation` (
  `itineraryID` VARCHAR(45) NOT NULL,
  `accommodationID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`itineraryID`, `accommodationID`),
  INDEX `fk_accommodation_ia_idx` (`accommodationID` ASC) VISIBLE,
  CONSTRAINT `fk_accommodation_ia`
    FOREIGN KEY (`accommodationID`)
    REFERENCES `globeDB`.`Accommodation` (`id`),
  CONSTRAINT `fk_itinerary_ia`
    FOREIGN KEY (`itineraryID`)
    REFERENCES `globeDB`.`Itinerary` (`itineraryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globeDB`.`requestAttraction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`requestAttraction` (
  `requestID` VARCHAR(45) NOT NULL,
  `attractionID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`requestID`, `attractionID`),
  INDEX `fk_attraction_ra_idx` (`attractionID` ASC) VISIBLE,
  CONSTRAINT `fk_attraction_ra`
    FOREIGN KEY (`attractionID`)
    REFERENCES `globeDB`.`Attraction` (`placeID`),
  CONSTRAINT `fk_request_ra`
    FOREIGN KEY (`requestID`)
    REFERENCES `globeDB`.`Request` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globeDB`.`requestCity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`requestCity` (
  `requestID` VARCHAR(45) NOT NULL,
  `cityID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`requestID`, `cityID`),
  INDEX `fk_city_rc_idx` (`cityID` ASC) VISIBLE,
  CONSTRAINT `fk_city_rc`
    FOREIGN KEY (`cityID`)
    REFERENCES `globeDB`.`City` (`placeID`),
  CONSTRAINT `fk_request_rc`
    FOREIGN KEY (`requestID`)
    REFERENCES `globeDB`.`Request` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `globeDB`.`requestType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `globeDB`.`requestType` (
  `requestID` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`requestID`, `type`),
  INDEX `fk_type_rt_idx` (`type` ASC) VISIBLE,
  CONSTRAINT `fk_request_rt`
    FOREIGN KEY (`requestID`)
    REFERENCES `globeDB`.`Request` (`id`),
  CONSTRAINT `fk_type_rt`
    FOREIGN KEY (`type`)
    REFERENCES `globeDB`.`Type` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
